use_frameworks!

platform :ios, '8.0'

target 'TestSDK_Example' do
  pod 'TestSDK', :path => '../'

  target 'TestSDK_Tests' do
    inherit! :search_paths
    #RAC响应式编程库
    pod 'ReactiveObjC'
    
    ##################################第三方###########################
    #YYModel--数组转模型组件
    pod 'YYModel'
    
    #YYCategories--给系统类添加的分类
    pod 'YYCategories'
    
    pod 'FMDB'
    pod 'MJExtension'
    
    pod 'AFNetworking', '3.1.0'
    
    pod 'SDAutoLayout'
    pod 'SAMKeychain'
  end
end
