use_frameworks!

platform :ios, '8.0'

target 'TestSDK_Example' do
  pod 'TestSDK', :path => '../'

  target 'TestSDK_Tests' do
    inherit! :search_paths
    #RAC响应式编程库
    pod 'ReactiveCocoa', '2.5'
    pod 'AFNetworking','3.1.0'
  end
end
